#!/usr/bin/env python3
"""
Update the version in __version__.py to match pyproject.toml.
This script should be run as part of the build process.
"""
import re
from pathlib import Path

def update_version():
    """Update __version__.py to match the version in pyproject.toml."""
    # Get the project root directory
    root = Path(__file__).parent.parent
    
    # Read version from pyproject.toml
    pyproject_path = root / 'pyproject.toml'
    with open(pyproject_path) as f:
        content = f.read()
    
    # Extract version using regex
    version_match = re.search(r'version\s*=\s*"([^"]+)"', content)
    if not version_match:
        raise ValueError("Could not find version in pyproject.toml")
    
    version = version_match.group(1)
    
    # Update __version__.py
    version_file = root / 'src' / 'dwellir_harvester_app' / '__version__.py'
    version_content = (
        f'# This file is auto-generated by {Path(__file__).name}. Do not edit manually.\n'
        f'__version__ = "{version}"\n'
    )
    
    version_file.parent.mkdir(parents=True, exist_ok=True)
    version_file.write_text(version_content)
    
    print(f'Updated version to {version} in {version_file.relative_to(root)}')

if __name__ == '__main__':
    update_version()
